/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendLeadRouteImport } from './routes/api.send-lead'

const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendLeadRoute = ApiSendLeadRouteImport.update({
  id: '/api/send-lead',
  path: '/api/send-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/api/send-lead': typeof ApiSendLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/api/send-lead': typeof ApiSendLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/api/send-lead': typeof ApiSendLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aviso-legal' | '/politica-privacidad' | '/api/send-lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aviso-legal' | '/politica-privacidad' | '/api/send-lead'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/politica-privacidad'
    | '/api/send-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  ApiSendLeadRoute: typeof ApiSendLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-lead': {
      id: '/api/send-lead'
      path: '/api/send-lead'
      fullPath: '/api/send-lead'
      preLoaderRoute: typeof ApiSendLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  ApiSendLeadRoute: ApiSendLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
